// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoK-UKy0D0xv3J5ej8_Fp8qLdx_NcqTG8',
    appId: '1:474686012074:android:0406226a6798a9e6c2eed3',
    messagingSenderId: '474686012074',
    projectId: 'steps-fec2d',
    databaseURL: 'https://steps-fec2d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'steps-fec2d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLo8Ppo1uh3AoNhnrV_Yb9ktY2j7CzseY',
    appId: '1:474686012074:web:1c9512abf9848156c2eed3',
    messagingSenderId: '474686012074',
    projectId: 'steps-fec2d',
    authDomain: 'steps-fec2d.firebaseapp.com',
    databaseURL: 'https://steps-fec2d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'steps-fec2d.firebasestorage.app',
  );
}